"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-04-03 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # table creation is expected to be generated by `alembic revision --autogenerate`


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
