"""add_intent_meta_token_count_to_messages

Revision ID: 14d415e7efd4
Revises: a8c78a0650e0
Create Date: 2026-05-14 02:34:32.736430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14d415e7efd4'
down_revision = 'a8c78a0650e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('intent', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'token_count')
    op.drop_column('messages', 'meta')
    op.drop_column('messages', 'intent')
    # ### end Alembic commands ###