"""add_name_and_size_to_knowledge_base

Revision ID: be6bd62e2f78
Revises: c3b93045e690
Create Date: 2026-04-23 01:12:17.547470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6bd62e2f78'
down_revision = 'c3b93045e690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('name', sa.String(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('kb_size', sa.Integer(), nullable=True))
    
    op.execute("""
        UPDATE knowledge_bases
        SET name = 'Name not provided', kb_size = 0
        WHERE name IS NULL
    """)
    
    op.alter_column('knowledge_bases', 'name', nullable=False)
    op.alter_column('knowledge_bases', 'kb_size', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'kb_size')
    op.drop_column('knowledge_bases', 'name')
    # ### end Alembic commands ###